CREATE TABLE security_alerts (
    alert_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    failed_attempts NUMBER NOT NULL,
    alert_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    alert_message VARCHAR2(255),
    notification_contact VARCHAR2(100)
);
